name: game

custom-setup:
  dependencies:
    - gloss

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  game:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -main-is Main
