name: game

custom-setup:
  dependencies:
    - gloss
    - GLUT
    - base
    - Cabal
    - JuicyPixels
    - bmp
    - gloss-juicy

dependencies:
  - base >= 4.7 && < 5
  - gloss
  - GLUT
  - JuicyPixels
  - bmp
  - gloss-juicy

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  game:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -main-is Main
