resolver: lts-20.23

packages:
  - ./game

extra-deps:
  - gloss-1.13.2.2
  - GLUT-2.7.0.16
  - JuicyPixels-3.3.8
  - vector-0.13.0.0
  - gloss-juicy-0.2.3

ghc-options:
  "$locals": -Wall -fno-warn-type-defaults
